[package]
name = "rsgeo-core"
version = "0.1.0"
authors = ["Yu Ri Tan"]
edition = "2018"

[dependencies]
geo = "0.15.0"
itertools = "0.9.0"
rand = "0.7.3"

[lib]
name = "rsgeo_core"
path = "src/lib.rs"