[package]
name = "coregeos"
version = "0.1.0"
authors = ["Yu Ri Tan"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
geo = "0.15.0"
itertools = "0.9.0"
rand = "0.7.3"
