name: Create Python release

on:
  push:
    # Sequence of patterns matched against refs/tags
    tags:
      - 'rsgeo-v*' # Push events to matching rsgeo-v*, i.e. rsgeo-v1.0, rsgeo-v20.15.10
jobs:
  test:
    name: Test Python bindings
    runs-on: "ubuntu-latest"
    strategy:
      matrix:
        python-version: ["3.6", "3.7", "3.8"]
    steps:
        - uses: actions/checkout@v2
        - name: Install latest Rust nightly
          uses: actions-rs/toolchain@v1
          with:
            toolchain: nightly-2020-11-12
            override: true
            components: rustfmt
        - name: Set up Python
          uses: actions/setup-python@v2
          with:
            python-version: ${{ matrix.python-version }}
        - name: Install dependencies
          run: |
            python -m pip install --upgrade pip
            pip install -r requirements.txt
        - name: Run tests
          run: |
            cd rsgeo-py
            make tests
            rm wheels/*
  build:
    needs: test
    name: Create Release
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: ["ubuntu-latest", "macos-latest", "windows-latest"]
        python-version: ["3.6", "3.7", "3.8"]
    steps:
        - uses: actions/checkout@v2
        - name: Install latest Rust nightly
          uses: actions-rs/toolchain@v1
          with:
            toolchain: nightly
            override: true
            components: rustfmt
        - name: Set up Python
          uses: actions/setup-python@v2
          with:
            python-version: ${{ matrix.python-version }}
        - name: Install dependencies
          run: |
            python -m pip install --upgrade pip
            pip install maturin
        - name: Publish wheel
          shell: bash
          env:
            MATURIN_PASSWORD: ${{ secrets.PYPI_PASS }}
          run: |
            cd rsgeo-py
            maturin publish \
            -o wheels \
            -i python \
            --username YuRiTan \

